let nome = "alberto ";
let sobreNome = "moiseis";
const sexo = "M";
let idade = 31;
let estuda = true;
console.log(typeof(nome));
console.log(typeof(sobreNome));
console.log(typeof(sexo));
console.log(typeof(idade));
console.log(typeof(estuda));
